Mentra-Community/MentraOS

- web_frontend/.env.local.copy
- web_frontend/src/App.tsx
- web_frontend/src/components/PageView.tsx
- web_frontend/src/components/SettingsModal.tsx
- web_frontend/src/components/TranscriptCard.tsx
- web_frontend/src/serverEndpoints.tsx
- Fixed the pause play issue
- Added a new env var `VITE_SERVER_ENVIRONMENT` to easily switch between dev and prod
- Added a button to open up a reference card in another tab if it does not allow embeds
> Fix pause play + server env variable + open custom data in new page

- server/ContextualSearchEngine.py
- server/DatabaseHandler.py
Updated transcript handling for the (hopefully but probably not) final time.
Still needs a backslider => will be added soon enough... Realistically within 4.3 hours of you reading this text.
> Transcript Handling V2

- server/custom_data/custom_data_example.csv
- server/server.py
- web_frontend/src/components/SettingsModal.tsx
Reenable uploading of custom data from web frontend.
Add error messages to frontend (eg: uploaded file too large).
Increase max uploaded file size from 32 => 88 MB.
> Fix custom data

- server/DatabaseHandler.py
* Only slide back on recent final transcripts (within 30s)
> * Ability to slide back over all final transcripts

- server/agent_insights_process.py
- server/agent_insights_prompts.py
- Optimized prompt to limit tool usage to just 1, making it ~5s faster
- Added a max iteration for the agent as a guard rail in case it decides to go in an infinite loop
> Optimized prompt and set hard limit to agent as guard rail

- server/tests/test_real_time_transcripts.py
Added a script that sends transcripts based on timestamps in real time
It sends the transcript in real time and gets the responses to the api calls
> Realtime transcripts test new

- server/agents/expert_agents.py
Added pydantic parsing and checking to ensure output is of the right structure
> Refactor expert agent response parsing

- chome_extension/background.js
- chome_extension/constants.js
- chome_extension/getYoutubeTranscript.js
- chome_extension/index.html
- chome_extension/manifest.json
- chome_extension/scriptf.js
- chome_extension/sidebar.html
- chome_extension/sidebar.js
- chome_extension/style.css
- server/DatabaseHandler.py
- server/server.py
- web_frontend/src/App.tsx
- web_frontend/src/hooks/useUiUpdateBackendPoll.ts
Add chrome_extension to chrome as unpacked extension.
This pulls YouTube's closed captions and sends them to /chat as userId=testUserId. Closed captions must be enabled.
TODO:
* Automatically load (if sidebar open) for new youtube video
* Automatically set userId
* Only check for captions when necessary
* Save recording as json via browser
How to start a recording: 
`localhost:8080/start_recording` => requires `userId` param
How to save/download/stop a recording:
`localhost:8080/save_recording` => requires `userId` and a `recordingName` param
> Chrome Extension + Recordings

- web_frontend/src/App.tsx
- web_frontend/src/components/ExplorePane.tsx
- web_frontend/src/layouts/StudyLayout.tsx
- web_frontend/src/recoil.ts
- web_frontend/src/types.ts
The Google Programmable Search component has to be set to "Two Page" for the component to display correctly.
> add custom google search condition

- web_frontend/src/components/ChatGPT.tsx
- web_frontend/src/layouts/StudyLayout.tsx
> Hide iframe after new google search

- web_frontend/src/layouts/StudyLayout.tsx
> add buttons to switch study condition

- android_app/app/src/main/java/com/teamopensmartglasses/convoscope/ConvoscopeService.java
- android_app/app/src/main/java/com/teamopensmartglasses/convoscope/MainActivity.java
- android_app/app/src/main/java/com/teamopensmartglasses/convoscope/ui/LandingUi.java
- android_app/app/src/main/java/com/teamopensmartglasses/convoscope/ui/SettingsUi.java
- android_app/app/src/main/res/layout/settings_fragment.xml
For use with `sgm_beta_improvements` SGM branch
https://github.com/TeamOpenSmartGlasses/SmartGlassesManager/pull/9
> Add "Audio only" slider & fix landing

- web_frontend/public/chat_bubbles_icon.svg
- web_frontend/src/App.tsx
- web_frontend/src/components/CardWrapper.tsx
- web_frontend/src/components/GoogleButton.tsx
- web_frontend/src/layouts/LandingPage.tsx
- web_frontend/src/layouts/MainLayout.tsx
- web_frontend/src/layouts/RootLayout.tsx
- web_frontend/src/theme.ts
> create landing page

- android_app/app/src/main/java/com/teamopensmartglasses/convoscope/ConvoscopeService.java
- android_app/app/src/main/java/com/teamopensmartglasses/convoscope/TokenHelper.java
- android_app/app/src/main/java/com/teamopensmartglasses/convoscope/convoscopebackend/BackendServerComms.java
- android_app/app/src/main/java/com/teamopensmartglasses/convoscope/ui/LandingUi.java
Contains...:
* Fix for auth bug
* Reduce UI Poll frequency when we haven't sent transcripts in >60s
> Android improvements

- android_app/app/build.gradle
- android_app/app/src/main/java/com/teamopensmartglasses/convoscope/Constants.java
- android_app/app/src/main/java/com/teamopensmartglasses/convoscope/ConvoscopeService.java
- server/DatabaseHandler.py
- server/agents/language_learning_agent.py
- server/agents/ll_word_suggest_upgrade.py
- server/agents/ll_word_suggest_upgrade_agent.py
- server/agents/ll_word_suggest_upgrade_agent_process.py
- server/agents/ll_word_suggest_upgrade_process.py
- server/server.py
- server/tests/test_helper.py
made changes to dbhandler, server, and convoscope service
> ll word suggest upgrade

- android_app/app/src/main/java/com/teamopensmartglasses/convoscope/ConvoscopeService.java
Must be run with: https://github.com/TeamOpenSmartGlasses/SmartGlassesManager/pull/21
> Change Font Size from Convoscope

- .github/workflows/main.yml
WIP Github workflow to deploy the dev cloud server
> [WIP 🚧] main.yml

- augmentos_cloud/bun.lock
- augmentos_cloud/package.json
- augmentos_cloud/packages/apps/dashboard-manager/package.json
- augmentos_cloud/packages/apps/flash/package.json
- augmentos_cloud/packages/apps/live-captions/package.json
- augmentos_cloud/packages/apps/miraai/package.json
- augmentos_cloud/packages/apps/notify/package.json
- augmentos_cloud/packages/cloud/package.json
- augmentos_cloud/packages/cloud/src/services/core/session.service.ts
- augmentos_cloud/packages/cloud/src/services/layout/DisplayManager.ts
- augmentos_cloud/packages/types/src/core/user.session.ts
Use tsx for dev to hopefully resolve issues
> Cloud/display manager WIP

- augmentos_android_library/AugmentOSLib/src/main/java/com/augmentos/augmentoslib/AugmentOSGlobalConstants.java
- augmentos_android_library/AugmentOSLib/src/main/java/com/augmentos/augmentoslib/SmartGlassesAndroidService.java
- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/AugmentosService.java
- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/NewPermissionUtils.java
- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/augmentos_backend/NetworkMonitor.java
- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/augmentos_backend/ServerComms.java
- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/augmentos_backend/WebSocketLifecycleManager.java
- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/augmentos_backend/WebSocketManager.java
- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/smarterglassesmanager/smartglassescommunicators/EvenRealitiesG1SGC.java
- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/smarterglassesmanager/smartglassesconnection/SmartGlassesAndroidService.java
- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/smarterglassesmanager/speechrecognition/augmentos/SpeechRecAugmentos.java
- augmentos_manager/android/app/build.gradle
- augmentos_manager/android/app/src/main/res/values/strings.xml
- augmentos_manager/app.json
- augmentos_manager/ios/AugmentOS_Manager/Info.plist
- augmentos_manager/src/BluetoothService.tsx
- augmentos_manager/src/components/Header.tsx
- augmentos_manager/src/logic/PermissionsUtils.tsx
- augmentos_manager/src/screens/Homepage.tsx
- augmentos_manager/src/screens/PhoneNotificationSettings.tsx
* Improve websocket reconnection logic
* Make websocket disconnection less jarring on frontend
* rename app to just AugmentOS
* Only show 1 notification
* Improve permissions flow
* Fix permissions issue impacting android 11 users
* reduce crashes in even realities ble system
> Various improvements for 2.0-beta-6

- augmentos_cloud/packages/cloud/src/routes/apps.routes.ts
- augmentos_cloud/packages/cloud/src/services/core/app.service.ts
- augmentos_cloud/packages/cloud/src/services/core/session.service.ts
- augmentos_cloud/packages/cloud/src/services/core/websocket.service.ts
- augmentos_cloud/store/web/src/hooks/useAuth.tsx
- augmentos_cloud/store/web/src/main.tsx
- augmentos_manager/src/backend_comms/BackendServerComms.tsx
- augmentos_manager/src/screens/AppStoreWebview.tsx
> Fix rest + App Store Works

- augmentos_cloud/packages/apps/dashboard-manager/src/index.ts
- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/AugmentosService.java
- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/statushelpers/JsonHelper.java
Fix for dashboard date/time when no location
TODO: iOS support
> Fix for dashboard date/time when no location

- .github/workflows/augmentos-manager-jest.yml
- augmentos_manager/.gitignore
- augmentos_manager/__tests__/App.test.tsx
- augmentos_manager/jest.config.js
- augmentos_manager/jest.config.ts
- augmentos_manager/jest.setup.ts
- augmentos_manager/package-lock.json
- augmentos_manager/package.json
- augmentos_manager/tsconfig.json
This uses the tests setup from @lohmuller as a basis for adding tests
> Pull in tests from lohmuller's fix/jester

- augmentos_cloud/bun.lock
- augmentos_cloud/packages/cloud/package.json
- augmentos_cloud/packages/cloud/src/services/layout/DisplayManager6.1.ts
- augmentos_cloud/packages/utils/package.json
- augmentos_cloud/packages/utils/src/PostHogTransport.ts
- augmentos_cloud/packages/utils/src/logger.ts
- augmentos_cloud/packages/utils/src/posthog.ts
Pushes warning and error log messages from cloud project to PostHog.  See examples:
https://us.posthog.com/project/128998/error_tracking
> Posthog Error Reporting

- augmentos_manager/android/app/build.gradle
Fixed missing AUGMENTOS_UPLOAD_STORE_PASSWORD keystore file.
> Fix Build gradle

- augmentos_cloud/packages/cloud/src/middleware/client/client-auth-middleware.ts
- augmentos_cloud/packages/cloud/src/middleware/glasses-auth.middleware.ts
- augmentos_cloud/packages/cloud/src/middleware/supabaseMiddleware.ts
- augmentos_cloud/packages/cloud/src/models/user.model.ts
- augmentos_cloud/packages/cloud/src/routes/apps.routes.ts
- augmentos_cloud/packages/cloud/src/routes/developer.routes.ts
- augmentos_cloud/packages/cloud/src/services/core/app.service.ts
- augmentos_cloud/packages/cloud/src/services/core/invite.service.ts
- augmentos_cloud/packages/cloud/src/services/core/organization.service.ts
- augmentos_cloud/packages/cloud/src/services/logging/pino-logger.ts
- augmentos_cloud/packages/sdk/src/types/enums.ts
Appstore auth fix when no session, removed some unused code, added todo's for other areas that need refactoring or further investigating
> Appstore auth fix when no session

- augmentos_cloud/packages/cloud/src/routes/tpa-settings.routes.ts
Fix issue with how TPA settings we're being fetched and combined with… users settings by cleaning the json before sending to client.
> Fix issue with Fetching TPA and user settings.

- augmentos_cloud/developer-portal/src/components/dialogs/CreateOrgDialog.tsx
- augmentos_cloud/developer-portal/src/pages/AuthPage.tsx
- augmentos_cloud/developer-portal/src/pages/EditTPA.tsx
- augmentos_cloud/developer-portal/src/pages/Members.tsx
- augmentos_cloud/developer-portal/src/pages/OrganizationSettings.tsx
- augmentos_cloud/developer-portal/src/services/api.service.ts
- augmentos_cloud/packages/cloud/src/models/organization.model.ts
- augmentos_cloud/packages/cloud/src/routes/organization.routes.ts
- augmentos_cloud/packages/cloud/src/services/core/organization.service.ts
manage invitations, better messaging, better ui, ability to make a new org, ability to leave an org
> clean up the way orgs work in dev console

- augmentos_docs/docs/core-concepts.md
- augmentos_docs/docs/getting-started.md
- augmentos_docs/docs/permissions.md
- augmentos_docs/docs/quickstart.md
- augmentos_docs/docs/railway-deployment.md
- augmentos_docs/docusaurus.config.ts
- augmentos_docs/sidebars.ts
Updates the documentation to have a page on permissions and how they work
> add permissions and railway to docs and expand getting started guide

- augmentos_cloud/store/web/src/hooks/useTheme.ts
- augmentos_cloud/store/web/src/index.css
- augmentos_cloud/store/web/src/pages/AppStore.tsx
> fix style issues with app store

- augmentos_cloud/packages/cloud/src/index.ts
- augmentos_cloud/packages/cloud/src/services/processing/transcription.service.ts
- augmentos_cloud/packages/cloud/src/services/websocket/websocket-app.service.ts
fixed duplicated event handlers in transcription service, added debounce for subscription change, and prevent infinite retries
> Azure ASR 4429

- augmentos_cloud/packages/cloud/src/models/user.model.ts
- augmentos_cloud/packages/cloud/src/services/websocket/websocket-glasses.service.ts
- augmentos_cloud/porter.yaml
> Fix cloud system settings 🔧☁️

- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/AugmentosService.java
- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/comms/AugmentOsActionsCallback.java
- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/comms/AugmentOsManagerMessageParser.java
- augmentos_core/app/src/main/java/com/augmentos/augmentos_core/smarterglassesmanager/eventbusmessages/ButtonPressEvent.java
- augmentos_manager/SIMULATED_GLASSES_CONTROLS_PLAN.md
- augmentos_manager/ios/BleManager/AOSManager.swift
- augmentos_manager/ios/BleManager/AOSModule.m
- augmentos_manager/ios/BleManager/ServerComms.swift
- augmentos_manager/src/app/mirror/fullscreen.tsx
- augmentos_manager/src/bridge/CoreCommunicator.android.tsx
- augmentos_manager/src/bridge/CoreCommunicator.ios.tsx
- augmentos_manager/src/components/glasses/DeviceSettings.tsx
- augmentos_manager/src/components/glasses/GlassesFeatureList.tsx
- augmentos_manager/src/components/misc/SimulatedGlassesControls.tsx
- augmentos_manager/src/config/glassesFeatures.ts
modified react native glasses capabilities list, only show phone/mic selector for glasses that have custom gatt mic
> fix mic settings

- asg_client/app/src/main/java/com/augmentos/asg_client/camera/CameraNeo.java
substantially improves auto exposure and auto focus on menta live
Fixes #720
> Simplify auto exposure

- cloud/packages/sdk/src/app/server/index.ts
- cloud/packages/sdk/src/app/webview/index.ts
- cloud/packages/sdk/src/types/index.ts
- cloud/packages/sdk/src/types/messages/cloud-to-app.ts
- docs/docs/reference/interfaces/tool-types.md
- docs/docs/tools.md
Adds the ability for tools to handle their own responses and also easily get the active session
> Make tool calling more flexible

- cloud/packages/cloud/src/services/session/transcription/providers/SonioxLanguages.json
- cloud/packages/cloud/src/services/session/transcription/providers/SonioxTranscriptionProvider.ts
- cloud/packages/sdk/src/index.ts
- cloud/packages/sdk/src/types/index.ts
- cloud/packages/sdk/src/types/messages/cloud-to-app.ts
transcript metadata  with token level confidence for soniox, and fix s…oniox transcription
> transcript metadata 

- mobile/src/components/misc/AppsInactiveList.tsx
- mobile/src/utils/PermissionsUtils.tsx
Fix app camera permission so it doesn't require actual phone camera permission
Fixes #948
> seperate the camera permission for glasses and app

- cloud/packages/cloud/src/index.ts
- cloud/packages/cloud/src/services/session/transcription/types.ts
- cloud/packages/sdk/src/app/session/index.ts
- cloud/packages/sdk/src/app/session/settings.ts
https://docs.google.com/document/d/1FkTEAgpPQeSWxKFWbZezWULzKWKJBGD7h2GAa-Vx3ic/edit?tab=t.0
> Better Stack Logger issues due to passing the wrong argument

- cloud/packages/cloud/src/services/session/MicrophoneManager.ts
send empty requiredData when isMicrophoneEnabled is false
> fix mic state change for ios,

- cloud/packages/cloud/src/middleware/client/client-auth-middleware.ts
- cloud/packages/cloud/src/routes/apps.routes.ts
- cloud/packages/sdk/src/app/session/index.ts
(cherry picked from commit 8effd00fc174511a99f38b570e1ae834e287f040)
> appstore home page loading fix

- cloud/websites/console/src/components/dialogs/DeleteDialog.tsx
You can now delete as many apps u want from the dev console.
> You can now delete as many apps you want
